--EJERCICIO_1
SELECT DISTINCT(BE.CEDULA), BE.NOMBRE ||' '|| BE.APELLIDO AS NOMBRE_COMPLETO, 
TO_CHAR(BP.SALARIO_BASICO,'999G999G999') SALARIO_BASICO,
TO_CHAR(BP.BONIFICACION_X_VENTAS,'999G999G999') BONIFICACION_X_VENTAS, 
TO_CHAR(BP.DESCUENTO_IPS,'999G999G999') DESCUENTO_IPS,
TO_CHAR(NVL(BP.SALARIO_BASICO - BP.DESCUENTO_IPS + BP.BONIFICACION_X_VENTAS,0), '999G999G999') MONTO_COBRADO,
TO_CHAR(NVL((BP.SALARIO_BASICO * 0.165),0),'999G999G999') AS IPS_PATRONAL,
TO_CHAR(NVL((BP.SALARIO_BASICO * 0.165 + BP.DESCUENTO_IPS),0),'999G999G999') MONTO_TOTAL_IPS
FROM B_EMPLEADOS be 
JOIN B_PLANILLA bp ON BE.CEDULA = BP.CEDULA
JOIN B_RECIBO_DINERO brd ON BRD.CED_EMPLEADO = BE.CEDULA
JOIN B_LIQUIDACION l ON l.id = bp.id_liquidacion
WHERE L.ANIO = 2025
AND L.MES = 8
ORDER BY 2;

--EJERCICIO_2
SELECT DISTINCT(a.ID), a.NOMBRE AS DESCRIPCION, dc.CANTIDAD
FROM B_DETALLE_compras dc
JOIN B_ARTICULOS a ON dc.ID_ARTICULO = A.ID
JOIN B_COMPRAS c ON c.ID = dc.ID_COMPRA 
JOIN B_PERSONAS bp ON C.ID_PROVEEDOR = BP.ID
WHERE EXTRACT(YEAR FROM c.FECHA) = 2025
ORDER BY 3 ASC
FETCH FIRST 5 ROWS ONLY;
